{
  "openapi": "3.1.0",
  "x-stoplight": {
    "id": "bx8v03jlmohm4"
  },
  "info": {
    "title": "Api documentation",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost/api/"
    }
  ],
  "paths": {
    "/register": {
      "post": {
        "summary": "Register",
        "operationId": "post-register",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "token": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "x-examples": {
                    "Example 1": {
                      "success": true,
                      "data": {
                        "token": "10|bbKplmTvrkJ71d7RU36IztFPvoQQcA9kdFRRskGJ",
                        "name": "name"
                      }
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "status": "success",
                      "data": {
                        "tokenType": "Bearer",
                        "expiresIn": 31622400,
                        "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiM2NmMmIzMjExYmY4YjVkNzBhMDljNDFkMWZkNmRjMDE3YTU1ZTFlMjk3Y2FlZTA1YzNlM2UyMzhlMWVjNGUyODBmZGU0ZjAyMjgwNmNiZmMiLCJpYXQiOjE2ODk4NzI4ODAuMzI2NTE4LCJuYmYiOjE2ODk4NzI4ODAuMzI2NTIsImV4cCI6MTcyMTQ5NTI4MC4zMDA0NDMsInN1YiI6IjIiLCJzY29wZXMiOltdfQ.j-lP1gmV7cxJkC_4co6532lmQR5HdOdIZLmu40xKuoDCcjHYOEAJ9pZKY3QMLgrjIerVBtxLV0Njylu6PJLlv6TA242dfKyoPI_3ujvPZtFx612wx5RSbwRbR7bUyM4BbwverC6wTHcxnYL8wmuB0bg7oXAP3Gh-pLYy0VXnZaaNlIRvGlhyaMj9DI33usIUiLVGokf4D37wc6IZIp4FDLD1_mYCytCsdKkGrzwbzT_F5TQrqonCcWCHNFBryG4Y3F2keDyR2phyVDQpqZvBIy4ymDOj7SCxK1S7XugVereqsLipnVQs-lAWXwCbv4f8sH17fsWbzoUF0SFraCEr-6DJwIsL8GnO24BepYRvqLqeFVV3W_8wurl_69_k7ztT2qdIZFj1YTojX2QS-xAszMprlUumbmZXfX1FOGzaoWLyIn6w2OpqyKX8Dg5yxxoqWlMQnz5GbqsGNaZJfJNGgDLmdXpWGL5ScHAMzZuqFYtYvtVicRlY-DfnejuaOISdXe2bZO8oKZQ5Hjfo_qLTacj4aODlwknUcCjyFhf6Scz4HgCEuB1XBkPUekLrszJOS9b8nGkZ8sJyjnFCzE7KRwLlj0aJ5iR7XVKM-v_HGU23Ie6INs0sH8I8y4BVaZpeuielP8CmSm1NGigJaLYgs4jsx0bhvtSx7T1QBHA0mtc",
                        "refreshToken": "def5020070cf93fc4716b596681d7e9f81ea9a2382a0c673cdbae27792c1f2f82deb88085bd845635a9709b94f28941179340305460fc3023b2b144b23d85973a03d7710284b0e0f856b6e786cccab19f0a23b1d0534623b9b4b83934fd086799b13b2e358299ea70f5abe80f15835fe7155afae3653a814f9947fe287f4a5b19982ece2a3362c1b55cf7d79ce36a9a00e4d85c48053f028fd8edfe4aee56cfd6dd4b8a5051d6a4bef8bdecf88cb9906ac47293f7a6e27081591e7e2199530879ed16600af202dddbcac4cc65042d08d9cdebab42c310e8fed5836138c543fd741b2146cfa3ee804ae978606128f1ff03e7a0c9d2ca09e4d1d9859c35b6d31e2cb2826ae21057b4dc33e8ec72d10cf84cd84b3c886bf3fcafc71a2d60b2e55e87b4feb59d61ae5df76db0765ef6dcec9450d8b2c898bd41941b165f5efe2046bcdedd17b4f5c92f3d41c5ed029aaf441b78c513706a595bff51c3c440545200be9",
                        "refreshTokenExpiresAt": 5183970
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "tags": [
          "Auth"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "c_password": {
                    "type": "string"
                  }
                },
                "x-examples": {
                  "Example 1": {
                    "name": "name",
                    "email": "mai2ss2332l@mail.com",
                    "password": "12345",
                    "c_password": "12345"
                  }
                }
              },
              "examples": {
                "Example 1": {
                  "value": {
                    "name": "name",
                    "email": "mai2ss2saf332l@mail.com",
                    "password": "12345",
                    "c_password": "12345"
                  }
                }
              }
            }
          },
          "description": ""
        },
        "parameters": []
      },
      "parameters": []
    },
    "/login": {
      "post": {
        "summary": "Register",
        "operationId": "post-register",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "token": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "x-examples": {
                    "Example 1": {
                      "success": true,
                      "data": {
                        "token": "10|bbKplmTvrkJ71d7RU36IztFPvoQQcA9kdFRRskGJ",
                        "name": "name"
                      }
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "success": true,
                      "data": {
                        "token": "11|fHXhuFunLOtTzi4VZBEZXMxcvzvd5GEurjGk8Tq6",
                        "name": "name"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "object",
                      "properties": {
                        "error": {
                          "type": "string"
                        }
                      }
                    },
                    "data": {
                      "type": "string"
                    }
                  },
                  "x-examples": {
                    "Example 1": {
                      "success": false,
                      "message": {
                        "error": "Unauthorised"
                      },
                      "data": "Unauthorised."
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "success": false,
                      "message": {
                        "error": "Unauthorised"
                      },
                      "data": "Unauthorised."
                    }
                  }
                }
              }
            }
          }
        },
        "tags": [
          "Auth"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "x-examples": {
                  "Example 1": {
                    "name": "name",
                    "email": "mai2ss2332l@mail.com",
                    "password": "12345",
                    "c_password": "12345"
                  }
                },
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Example 1": {
                  "value": {
                    "email": "mai2ss2saf332l@mail.com",
                    "password": "12345"
                  }
                }
              }
            }
          },
          "description": ""
        },
        "parameters": []
      },
      "parameters": []
    },
    "/adult/children": {
      "post": {
        "summary": "Store child",
        "operationId": "post-child",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "token": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "x-examples": {
                    "Example 1": {
                      "success": true,
                      "data": {
                        "token": "20|M29nroDSGrF6iFKc3SfqeZR3nkdB6ifQkfyRRyxv",
                        "name": "test2"
                      }
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "success": true,
                      "data": {
                        "token": "20|M29nroDSGrF6iFKc3SfqeZR3nkdB6ifQkfyRRyxv",
                        "name": "test2"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "object",
                      "properties": {
                        "error": {
                          "type": "string"
                        }
                      }
                    },
                    "data": {
                      "type": "string"
                    }
                  },
                  "x-examples": {
                    "Example 1": {
                      "success": false,
                      "message": {
                        "error": "Unauthorised"
                      },
                      "data": "Unauthorised."
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "success": false,
                      "message": {
                        "error": "Unauthorised"
                      },
                      "data": "Unauthorised."
                    }
                  }
                }
              }
            }
          },
          "422": {
            "$ref": "#/components/responses/422"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "age": {
                    "type": "integer"
                  },
                  "gender": {
                    "type": "integer"
                  },
                  "adult_type": {
                    "type": "string"
                  }
                },
                "x-examples": {
                  "Example 1": {
                    "name": "test2",
                    "age": 7,
                    "gender": 1,
                    "adult_type": "Grandma"
                  }
                }
              },
              "examples": {
                "Example 1": {
                  "value": {
                    "name": "test2",
                    "age": 7,
                    "gender": 1,
                    "adult_type": "Grandma"
                  }
                }
              }
            }
          },
          "description": ""
        },
        "parameters": [
          {
            "$ref": "#/components/parameters/Accept"
          }
        ],
        "tags": [
          "Children"
        ]
      },
      "parameters": [],
      "get": {
        "summary": "Get children",
        "operationId": "get-adult-children",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "name": {
                            "type": "string"
                          },
                          "age": {
                            "type": "integer"
                          },
                          "gender": {
                            "type": "integer"
                          },
                          "created_at": {
                            "type": "string"
                          },
                          "updated_at": {
                            "type": "string"
                          },
                          "pivot": {
                            "type": "object",
                            "properties": {
                              "adult_id": {
                                "type": "integer"
                              },
                              "child_id": {
                                "type": "integer"
                              },
                              "adult_type": {
                                "type": "string"
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "x-examples": {
                    "Example 1": {
                      "success": true,
                      "data": [
                        {
                          "id": 1,
                          "name": "Dr. Luciano Jenkins I",
                          "age": 8,
                          "gender": 0,
                          "created_at": "2023-08-14T19:46:49.000000Z",
                          "updated_at": "2023-08-14T19:46:49.000000Z",
                          "pivot": {
                            "adult_id": 1,
                            "child_id": 1,
                            "adult_type": "Grandma"
                          }
                        },
                        {
                          "id": 16,
                          "name": "test2",
                          "age": 7,
                          "gender": 1,
                          "created_at": "2023-08-14T21:50:06.000000Z",
                          "updated_at": "2023-08-14T21:50:06.000000Z",
                          "pivot": {
                            "adult_id": 1,
                            "child_id": 16,
                            "adult_type": "Grandma"
                          }
                        }
                      ]
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "success": true,
                      "data": [
                        {
                          "id": 1,
                          "name": "Dr. Luciano Jenkins I",
                          "age": 8,
                          "gender": 0,
                          "created_at": "2023-08-14T19:46:49.000000Z",
                          "updated_at": "2023-08-14T19:46:49.000000Z",
                          "pivot": {
                            "adult_id": 1,
                            "child_id": 1,
                            "adult_type": "Grandma"
                          }
                        },
                        {
                          "id": 16,
                          "name": "test2",
                          "age": 7,
                          "gender": 1,
                          "created_at": "2023-08-14T21:50:06.000000Z",
                          "updated_at": "2023-08-14T21:50:06.000000Z",
                          "pivot": {
                            "adult_id": 1,
                            "child_id": 16,
                            "adult_type": "Grandma"
                          }
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "x-examples": {
                    "Example 1": {
                      "message": "Unauthenticated."
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "message": "Unauthenticated."
                    }
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "$ref": "./admin.json#/components/parameters/Accept"
          }
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "tags": [
          "Children"
        ]
      }
    },
    "/adult/children/{child}": {
      "get": {
        "summary": "Show child by id",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "name": {
                          "type": "string"
                        },
                        "age": {
                          "type": "integer"
                        },
                        "gender": {
                          "type": "integer"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "x-examples": {
                    "Example 1": {
                      "success": true,
                      "data": {
                        "id": 1,
                        "name": "Dr. Luciano Jenkins I",
                        "age": 8,
                        "gender": 0,
                        "created_at": "2023-08-14T19:46:49.000000Z",
                        "updated_at": "2023-08-14T19:46:49.000000Z"
                      }
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "success": true,
                      "data": {
                        "id": 1,
                        "name": "Dr. Luciano Jenkins I",
                        "age": 8,
                        "gender": 0,
                        "created_at": "2023-08-14T19:46:49.000000Z",
                        "updated_at": "2023-08-14T19:46:49.000000Z"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/401"
          },
          "422": {
            "$ref": "#/components/responses/422"
          }
        },
        "operationId": "get-child",
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/Accept"
          }
        ],
        "tags": [
          "Children"
        ]
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "child",
          "in": "path",
          "required": true
        }
      ],
      "put": {
        "summary": "Update child",
        "operationId": "update-child",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "name": {
                          "type": "string"
                        },
                        "age": {
                          "type": "integer"
                        },
                        "gender": {
                          "type": "integer"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "x-examples": {
                    "Example 1": {
                      "success": true,
                      "data": {
                        "id": 1,
                        "name": "testssss2221321",
                        "age": 7,
                        "gender": 1,
                        "created_at": "2023-08-14T19:46:49.000000Z",
                        "updated_at": "2023-08-20T18:36:38.000000Z"
                      }
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "success": true,
                      "data": {
                        "id": 1,
                        "name": "testssss2221321",
                        "age": 7,
                        "gender": 1,
                        "created_at": "2023-08-14T19:46:49.000000Z",
                        "updated_at": "2023-08-20T18:36:38.000000Z"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "x-examples": {
                    "Example 1": {
                      "message": "Unauthenticated."
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "message": "Unauthenticated."
                    }
                  }
                }
              }
            }
          }
        },
        "tags": [
          "Admin groups"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "age": {
                    "type": "integer"
                  },
                  "gender": {
                    "type": "integer"
                  }
                },
                "x-examples": {
                  "Example 1": {
                    "name": "testssss2221321",
                    "age": 7,
                    "gender": 1
                  }
                }
              },
              "examples": {
                "Example 1": {
                  "value": {
                    "name": "testssss2221321",
                    "age": 7,
                    "gender": 1
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/components/parameters/Accept"
          }
        ]
      },
      "delete": {
        "summary": "Delete child",
        "operationId": "delete-child",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "x-examples": {
                    "Example 1": {
                      "success": true,
                      "message": "Child was deleted!"
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "success": true,
                      "message": "Child was deleted!"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "x-examples": {
                    "Example 1": {
                      "message": "Unauthenticated."
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "message": "Unauthenticated."
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ],
        "description": "",
        "parameters": [
          {
            "$ref": "#/components/parameters/Accept"
          }
        ],
        "tags": [
          "Children"
        ]
      }
    },
    "/adult/get_child_token/{child}": {
      "get": {
        "summary": "Get child token",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "token": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "x-examples": {
                    "Example 1": {
                      "success": true,
                      "data": {
                        "token": "26|yLrY0CmlR5RmUgtHx6YGWUjlg5JcCgDO2ALryJ0t",
                        "name": "Jeff Hauck"
                      }
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "success": true,
                      "data": {
                        "token": "26|yLrY0CmlR5RmUgtHx6YGWUjlg5JcCgDO2ALryJ0t",
                        "name": "Jeff Hauck"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/401"
          }
        },
        "operationId": "get-child-token",
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/Accept"
          }
        ],
        "tags": [
          "Children"
        ]
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "child",
          "in": "path",
          "required": true
        }
      ]
    },
    "/adult/regular_tasks/general_avalable_tasks": {
      "get": {
        "summary": "Show general available regular tasks",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "name": {
                          "type": "string"
                        },
                        "age": {
                          "type": "integer"
                        },
                        "gender": {
                          "type": "integer"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "x-examples": {
                    "Example 1": {
                      "success": true,
                      "data": {
                        "id": 1,
                        "name": "Dr. Luciano Jenkins I",
                        "age": 8,
                        "gender": 0,
                        "created_at": "2023-08-14T19:46:49.000000Z",
                        "updated_at": "2023-08-14T19:46:49.000000Z"
                      }
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "success": true,
                      "data": {
                        "id": 1,
                        "name": "Dr. Luciano Jenkins I",
                        "age": 8,
                        "gender": 0,
                        "created_at": "2023-08-14T19:46:49.000000Z",
                        "updated_at": "2023-08-14T19:46:49.000000Z"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/401"
          },
          "422": {
            "$ref": "#/components/responses/422"
          }
        },
        "operationId": "get-child",
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/Accept"
          }
        ],
        "tags": [
          "Children"
        ]
      },
      "parameters": [],
      "delete": {
        "summary": "Delete regular tasks",
        "operationId": "delete-regular_tasks",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "x-examples": {
                    "Example 1": {
                      "tasks": [
                        4
                      ]
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "success": true,
                      "message": "Child was deleted!"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ],
        "description": "",
        "parameters": [
          {
            "$ref": "#/components/parameters/Accept"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "tasks": {
                    "type": "array",
                    "items": {
                      "type": "integer"
                    }
                  }
                },
                "x-examples": {
                  "Example 1": {
                    "tasks": [
                      4,
                      2,
                      5
                    ]
                  }
                }
              },
              "examples": {
                "Example 1": {
                  "value": {
                    "tasks": [
                      5,
                      6,
                      7
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Store regular tasks for child",
        "operationId": "post-adult-regular_tasks-general_avalable_tasks",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    }
                  },
                  "x-examples": {
                    "Example 1": {
                      "success": true
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "success": true
                    }
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "$ref": "./admin.json#/components/parameters/Accept"
          }
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "tasks": {
                    "type": "array",
                    "items": {
                      "type": "integer"
                    }
                  },
                  "child_id": {
                    "type": "integer"
                  }
                },
                "x-examples": {
                  "Example 1": {
                    "tasks": [
                      1,
                      2,
                      3
                    ],
                    "child_id": 5
                  }
                }
              },
              "examples": {
                "Example 1": {
                  "value": {
                    "tasks": [
                      1,
                      2,
                      3
                    ],
                    "child_id": 5
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {
      "Authorization": {
        "type": "http",
        "scheme": "bearer"
      }
    },
    "parameters": {
      "Accept": {
        "name": "Accept",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "default": "application/json",
          "example": "application/json"
        },
        "description": "application/json"
      }
    },
    "requestBodies": {},
    "responses": {
      "401": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "message": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                },
                "data": {
                  "type": "string"
                }
              },
              "x-examples": {
                "Example 1": {
                  "success": false,
                  "message": {
                    "error": "Unauthorised"
                  },
                  "data": "Unauthorised."
                }
              }
            },
            "examples": {
              "Example 1": {
                "value": {
                  "success": false,
                  "message": {
                    "error": "Unauthorised"
                  },
                  "data": "Unauthorised."
                }
              }
            }
          }
        }
      },
      "422": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "properties": {
                "id": {
                  "type": "string"
                }
              }
            }
          },
          "application/xml": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "errors": {
                  "type": "object",
                  "properties": {
                    "age": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  }
                }
              },
              "x-examples": {
                "Example 1": {
                  "message": "The age field must be an integer.",
                  "errors": {
                    "age": [
                      "The age field must be an integer."
                    ]
                  }
                }
              }
            },
            "examples": {
              "Example 1": {
                "value": "{\n    \"message\": \"The age field must be an integer.\",\n    \"errors\": {\n        \"age\": [\n            \"The age field must be an integer.\"\n        ]\n    }\n}"
              }
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Children"
    }
  ],
  "security": [
    {
      "Authorization": []
    }
  ]
}